[aws]
disabled = true

[character]
format = "❯❯ "
success_symbol = "❯❯(bold green) "
error_symbol = "❯❯(bold red) "

[cmd_duration]
style = "yellow"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
style = "bold cyan"

[git_branch]
style = "purple"

[java]
style = "bold red"

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "+9"
style = "green"
